### ISSUE TITLE
Infinispan as JCache provider for HTTP session replication

### ISSUE THREAD

**Issue by corporate-gadfly** [OpenLiberty/draft-guide-sessions#145]
Is there a possibility for a similar HTTP session replication guide but with Infinispan _(instead of hazelcast)_ as JCache provider?

**Comment by gkwan-ibm** [comment]
Look like it is possible. I opened the [issue](https://github.com/OpenLiberty/guides-common/issues/804). It is in the backlog and will be prioritized accordingly unless someone will contribute.

**Comment by gkwan-ibm** [comment]
close
- this issue will be addressed by the issue in the above comment
