### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-sessions#21]
- The included picture isn't scaled correctly.  This needs to be fixed before we publish (so we aren't ready for sign-off yet).

- What you'll learn:  We should describe the intention of the guide and the concepts before introducing what the users will work with and what they will do.  Reorganize the "What is" sections to the top before the paragraph introducing the microservices included at the minimum; Consider appropriate revision given the reorganization too.

- Clarify and emphasize considerations needed for "caching HTTP sessions" (e.g. vs the use of the sessionCache feature or creating a service).

@evelinec @gkwan-ibm

**Comment by evelinec** [comment]
Followed up on item 1, targeting to get it ready in the next 2 weeks.

**Comment by evelinec** [comment]
The image had been updated with the one from design. The UI code is able to scale the image properly. Just we cannot test the image copying mechanism locally. Steven is working on providing the test site to test that.

**Comment by gkwan-ibm** [comment]
- content was rewritten
