### ISSUE TITLE
YK's review feedback

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-sessions#24]
YK's review feedback: 
- [ ] What you'll learn: We should describe the intention of the guide and the concepts before introducing what the users will work with and what they will do. Reorganize the "What is" sections to the top before the paragraph introducing the microservices included at the minimum; Consider appropriate revision given the reorganization too.

- [ ] Clarify and emphasize considerations needed for "caching HTTP sessions" (e.g. vs the use of the sessionCache feature or creating a service).

**Comment by gkwan-ibm** [comment]
- the content was rewritten
