### ISSUE TITLE
Strengthen the application and the scenario

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-sessions#33]
The existing app and scenario (1 microservice runs under 2 servers) to demonstrate the session caching is not a good practice. If using 1 microservice and run under a Kube cluster with multiple nodes may be a better practice, but it is so complicated.

To make the scenario more convenient, suggest to have 2 microservices run in 2 different servers, to demonstrate how the session caching work in both sides.

**Comment by justineechen** [comment]
Addressed in the dev branch
