### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by DannyS03** [OpenLiberty/draft-guide-sessions#37]
Peer Review: review to be done by a peer member. 

- [x] Check that the guide has working instruction and sample code
- [x] Check the quality of code according to the best coding practices
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide

Peer Testing: tests to be done by a peer member.

Guide's contributor's (if available, otherwise peer tester's) responsibility: 
- [x] Define test coverage and review with team (including guide contributor, if available)
- [x] Define detail test cases 
- [x] Consider corner cases targeting the specific guide
- [x] Consider different platform tests, ie, Mac, Windows, Linux
- [x] Consider corner cases UI tests
- [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
- [x] Consider testing the `curl` command for URL visits
- [x] Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, VS.code, Eclipse, IntelliJ, Microclimate
- [x] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [x] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [x] Ensure that the automation tests are able to run with continuous daily builds

Peer Tester's responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
- Table of contents 
- Headings
- Paragraphs
- code snippets
- outputs
- links
- hotspots
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by DannyS03** [comment]
**GRAMMER EDITS** 

* What You'll Learn 
- Perhaps "Session variables are maintained on a web server." before "By default, session variables will time out after 30 minutes of being unused."
- Reword the ending of the section and mention the difference between session variables and cookies. For instance, "Cookies store user information on the actual browser, whereas session variables store data on a server".

``` 
 Session variables store user information like user name or items in a shopping cart. By default, session variables will time out after 30 minutes of being unused. Session variables are maintained on a web server. Cookies, which also store user information, are maintained on a client’s computer. For security reasons, using session is preferred over using cookies for sensitive data. Session hides data from users. Cookies store data on client’s computer, and can be manipulated by a savvy user to make fake requests to your site.
```


'where' it can be instead of 'and' it can be
```
Application containerization is to bundle an application with all of its required libraries, dependencies, and configuration files, so that it can run in any containerization ecosystem, such as Docker, and it can be deployed to Kubernetes.
```


Comma after annotations
```
The addToCart and getCart methods have a number of annotations most of which are used by the mpOpenAPI and jaxrs features to provide context to the user interface and map java objects to web resources. More information about these annotations can be found in the Documenting RESTful APIs and Creating a RESTful web service guides.
```

**Comment by DannyS03** [comment]
**UI Enhancement**
- [ ] Diagram looks small on the web browser 

![image](https://user-images.githubusercontent.com/25497083/59440486-101e3680-8dc5-11e9-9974-f9c678153391.png)

**Comment by justineechen** [comment]
> Perhaps an introductory sentence on JCache would be more helpful for the user

- There is an introductory sentence in the section that focuses on JCache

>Perhaps an introductory sentence about JAVA API for RESTful web services would be more helpful for the user

- We linked the rest-intro guide a couple of sentences down for more info for the user

**Comment by justineechen** [comment]
**UI ENHANCEMENT**

- Once the table of contents is collapsed, the image isn't that small

<img width="1641" alt="Screen Shot 2019-06-17 at 10 04 25 AM" src="https://user-images.githubusercontent.com/18709242/59610419-5b975400-90e7-11e9-9adb-9e1b3b343d4a.png">

**Comment by DannyS03** [comment]
Right that's true! Though what if the user wants to have the TOC open all the time... or not really an issue?

**Comment by DannyS03** [comment]
> > Perhaps an introductory sentence on JCache would be more helpful for the user
> 
> * There is an introductory sentence in the section that focuses on JCache
> 
> > Perhaps an introductory sentence about JAVA API for RESTful web services would be more helpful for the user
> 
> * We linked the rest-intro guide a couple of sentences down for more info for the user

Isn't it usually better writing practice to introduce something and then talk about it later, rather then just talk about it later

**Comment by justineechen** [comment]
> "installation phase" sounds better than "install phase"

- The phase is called `install` and the command would be `mvn install` so I think it's clearer this way

>"Right that's true! Though what if the user wants to have the TOC open all the time... or not really an issue?" 

- If this is a concern we can open an issue for the design team
