### ISSUE TITLE
SME Review

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-sessions#39]
SME Review:

Review of the guide by a Subject Matter Expert (SME) for technical accuracy and content.

- [x] Ensure technical accuracy for code
- [x] Ensure technical accuracy for guide
- [x] Ensure technical accuracy for overall content

**Comment by zhang-ca** [comment]
Looks good.  By the way, "session variables" are same as "session data".

**Comment by zhang-ca** [comment]
Under the "Prerequisites" section, I suggest you add the following tools in additional to Docker: 

-Java SDK
-Git runtime
-Maven
