### ISSUE TITLE
Clarification for "Try it out" instructions

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-sessions#43]
For the 2 occurrences of the below:

```
Make a POST request to /cart/{item}&{price} by expanding the POST endpoint on the UI and clicking the Try it out button. The POST request adds a user specified item and price to a session that represents data in a user’s cart.
```

We should clarify that users should provide an item and a price before they click on "Try it out".

@justineechen @gkwan-ibm

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/draft-guide-sessions/commit/a4b5f29cfa90b6f8512748e2d502686fd29b178c

**Comment by yeekangc** [comment]
There are 2 places that can use clarification.  The commit above only fixed one.  There is another spot under "Building and running the application".

**Comment by gkwan-ibm** [comment]
updated by https://github.com/OpenLiberty/draft-guide-sessions/commit/5334f48b7205fff36dfd9f14230da6a70c23d432
