### ISSUE TITLE
ID review feedback

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/draft-guide-sessions#45]
My review notes and feedback are outlined in the attached Word document. My comments/questions are highlighted in yellow. Please let me know if you have any questions. Let me know when updates have been made, and I'll review them. Thanks!!

[Caching HTTP Session Data Guide Comments.docx](https://github.com/OpenLiberty/draft-guide-sessions/files/3399258/Caching.HTTP.Session.Data.Guide.Comments.docx)

**Comment by evelinec** [comment]
@justineechen @gkwan-ibm FYI.
